### PR TITLE
Migrate androidx

### LINKED ISSUE #96: androidX
When wiil it be on AndroidX ?

### PR DESCRIPTION
**Pull request by miguelbcr**
This PR migrates the codebase to AndroidX 

https://developer.android.com/jetpack/androidx/migrate

Closes https://github.com/miguelbcr/RxPaparazzo/issues/96

### CODE REVIEW

**Comment by JamesMcIntosh** [comment]
Hi @miguelbcr! Just wondering if you noticed that the uCrop dependency still doesn't have an AndroidX support release (though it is in their feature branches), not sure if this affects this code as it's run as a separate activity.

**Comment by miguelbcr** [comment]
Hi @JamesMcIntosh ! 
As far as I know since they are separate activities it won't be a problem. Just tested it and it worked fine.

**Comment by Zhuinden** [comment]
But was this ever released?

If you depend on `uCrop` and that is still android.support-based, then it will still require Jetifier.

**Comment by miguelbcr** [comment]
@Zhuinden 
nope, I only uploaded the migration to Android X but I never released it ...

**Comment by JamesMcIntosh** [comment]
@miguelbcr UCrop 2.2.4 has AndroidX compatibility too so you can bump the dependency up to the new version

**Pull request merged**
